services:
  mltoolsbot:
    container_name: mltoolsbot
    restart: unless-stopped
    env_file:
      - .env
    image: registry.frants.tech/mltoolsbot:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # networks:
    #   - mltoolsbot_net
    # depends_on:
    #   redis:
    #     condition: service_healthy
#   redis:
#     image: redis:latest
#     container_name: users_data
#     restart: unless-stopped
#     volumes:
#       - ./data:/data
#       - ./redis-init.sh:/redis-init.sh
#     networks:
#       - mltoolsbot_net
#     env_file:
#       - .env
#     entrypoint: ["/bin/sh", "-c", "chmod +x /redis-init.sh && /redis-init.sh"]
#     healthcheck:
#       test: ["CMD", "redis-cli", "ping"]
#       interval: 10s
#       timeout: 5s
#       retries: 3
#       start_period: 30s

# networks:
#   mltoolsbot_net:
#     driver: bridge
