version: "3"

services:
  MLToolsBot:
    image: registry.frants.site/mltoolsbot:latest
    # environment:
    #   - BOT_TOKEN = ${BOT_TOKEN}
    #   - CHAT_ID = ${CHAT_ID}
    #   - SD_SERVER_URL = ${SD_SERVER_URL}
    # env_file:
    #   - .env
