services:
  mltoolsbot:
    container_name: mltoolsbot
    restart: unless-stopped
    env_file:
      - .env
    image: ghcr.io/whoknowswhocares/mltoolsbot:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    networks:
      - mltoolsbot_net
    depends_on:
      redis:
        condition: service_healthy

  redis:
    container_name: users_data
    restart: unless-stopped
    image: redis:latest
    # ports:
    #   - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./data:/data
    networks:
      - mltoolsbot_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  mltoolsbot_net:
    driver: bridge
