version: "3.8"
services:
  MLToolsBot:
    container_name: mltoolsbot
    restart: always
    env_file:
      - .env
      # - prod.env
    image: registry.frants.site/mltoolsbot:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
