# Generated by CodiumAI
from main import call_api_g4f

import pytest


class TestText2text:
    # Generates a response from the G4F API when given a valid message.
    @pytest.mark.asyncio
    async def test_valid_message_response(self):
        message = "Hello, how are you?"
        response = await call_api_g4f(message)
        assert isinstance(response, str)
        assert response != ""
