name: Docker Image CI

on:
  push:
    branches: ["master", "prod"]
  pull_request:
    branches: ["master", "prod"]

env:
  BOT_TOKEN: ${{secrets.BOT_TOKEN}}
  CHAT_ID: ${{secrets.CHAT_ID}}
  SD_SERVER_URL: ${{secrets.SD_SERVER_URL}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile
