name: Docker Build

on:
  push:
    branches: ["master", "prod"]
  pull_request:
    branches: ["master", "prod"]

env:
  REGISTRY: registry.frants.tech
  IMAGE_NAME: mltoolsbot

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to my Registry (${{ env.REGISTRY }})
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Find Package Version
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build And Push Backend
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          outputs: type=oci,dest=/tmp/image.tar

      - name: Import image in containerd
        run: |
          sudo ctr i import --base-name ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} --digests --all-platforms /tmp/image.tar

      - name: Push image with containerd
        run: |
          sudo ctr --debug i push --user "${{ secrets.REGISTRY_USERNAME }}:${{ secrets.REGISTRY_PASSWORD }}" ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
