name: Deploy by Runner

on:
  workflow_run:
    workflows: ["Docker Build"]
    branches: ["prod"]
    types:
      - completed

env:
  ENV_FILE: .env

jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "docker-compose.yml"
      - name: Stop containers
        if: steps.check_files.outputs.files_exists == 'true'
        run: docker compose down
      - name: Remove unused data
        run: docker system prune -a -f
      - name: Cleanup build folder
        run: |
          rm -rf ./* || true

  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: Checkout docker-compose file
        uses: actions/checkout@v4
        with:
          ref: prod
          sparse-checkout: |
            docker-compose.yml
          sparse-checkout-cone-mode: false
      - name: Create env file
        run: |
          touch ${{ env.ENV_FILE }}
          echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> ${{ env.ENV_FILE }}
          echo ANTHROPIC_TOKEN=${{ secrets.ANTHROPIC_TOKEN }} >> ${{ env.ENV_FILE }}
          echo ELEVENLABS_TOKEN=${{ secrets.ELEVENLABS_TOKEN }} >> ${{ env.ENV_FILE }}
          echo LLM_SERVER_URL=${{ secrets.LLM_SERVER_URL }} >> ${{ env.ENV_FILE }}
          echo SD_SERVER_URL=${{ secrets.SD_SERVER_URL }} >> ${{ env.ENV_FILE }}
          echo REDIS_DEFAULTS=${{ secrets.REDIS_DEFAULTS }} >> ${{ env.ENV_FILE }}

      - name: Run docker-compose
        run: docker compose up -d
