name: Deploy by Runner

on:
  workflow_run:
    workflows: ["Tests", "Docker Build"]
    branches: ["master", "prod"]
    types:
      - completed

jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: Stop and remove containers, networks
        run: docker compose down
      - name: Remove unused data
        run: docker system prune -a -f
      - name: Cleanup build folder
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true

  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: Create env file
        run: |
          touch .env
          echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
          echo CHAT_ID=${{ secrets.CHAT_ID }} >> .env
          echo SD_SERVER_URL=${{ secrets.SD_SERVER_URL }} >> .env
      - name: Create docker-compose
        run: |
          touch docker-compose.yml
          echo -e "version:\"3\"" >> docker-compose.yml
          echo -e "services:" >> docker-compose.yml
          echo -e "  MLToolsBot:" >> docker-compose.yml
          echo -e "    image: registry.frants.site/mltoolsbot:latest" >> docker-compose.yml
          echo -e "    env_file: .env" >> docker-compose.yml
      - name: Run docker-compose
        run: docker compose up -d
